volumes:
  postgres:
  openfga_postgres:
  kratos_postgres:

services:
  postgres:
    extends:
      file: docker-compose-base.yml
      service: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    profiles:
      - 'dev'

  openfga-postgres:
    extends:
      file: docker-compose-base.yml
      service: openfga-postgres
    volumes:
      - openfga_postgres:/var/lib/postgresql/data
    profiles:
      - 'dev'

  openfga-migrate:
    extends:
      file: docker-compose-base.yml
      service: openfga-migrate
    depends_on:
      openfga-postgres:
        condition: service_healthy
    profiles:
      - 'dev'

  openfga:
    extends:
      file: docker-compose-base.yml
      service: openfga
    depends_on:
      openfga-migrate:
        condition: service_completed_successfully
    environment:
      OPENFGA_TRACE_ENABLED: 'true'
      OPENFGA_TRACE_OTLP_ENDPOINT: collector:4317
      OPENFGA_TRACE_OTLP_TLS_ENABLED: 'false'
    command: run
    profiles:
      - 'dev'

  kratos-postgres:
    extends:
      file: docker-compose-base.yml
      service: kratos-postgres
    volumes:
      - kratos_postgres:/var/lib/postgresql/data
    profiles:
      - 'dev'

  kratos-migrate:
    extends:
      file: docker-compose-base.yml
      service: kratos-migrate
    depends_on:
      kratos-postgres:
        condition: service_healthy
    profiles:
      - 'dev'

  kratos:
    extends:
      file: docker-compose-base.yml
      service: kratos
    depends_on:
      kratos-migrate:
        condition: service_completed_successfully
      collector:
        condition: service_started
    profiles:
      - 'dev'

  kratos-selfservice-ui-node:
    extends:
      file: docker-compose-base.yml
      service: kratos-selfservice-ui-node
    profiles:
      - 'dev'

  mailslurper:
    extends:
      file: docker-compose-base.yml
      service: mailslurper
    profiles:
      - 'dev'

  collector:
    extends:
      file: docker-compose-base.yml
      service: collector
    depends_on:
      - zipkin
    profiles:
      - 'dev'

  zipkin:
    extends:
      file: docker-compose-base.yml
      service: zipkin
    profiles:
      - 'dev'

  prometheus:
    extends:
      file: docker-compose-base.yml
      service: prometheus
    profiles:
      - 'dev'
