volumes:
  postgres:
  openfga_postgres:
  kratos_postgres:
  node_modules:
  nx_cache:

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    user: node
    volumes:
      - ..:/home/node:cached
      # - node_modules:/home/node/node_modules
      - nx_cache:/home/node/.nx
      - /var/run/docker.sock:/var/run/docker.sock

    # Overrides default command so things don't shut down after the process ends
    command: sleep infinity

    # Network mode host is required for Docker in Docker to work properly
    network_mode: service:postgres

    # Use init to handle signals properly
    init: true

    depends_on:
      - postgres
      - openfga
      - kratos

  postgres:
    extends:
      file: ../docker-compose-base.yml
      service: postgres
    volumes:
      - postgres:/var/lib/postgresql/data

  openfga-postgres:
    extends:
      file: ../docker-compose-base.yml
      service: openfga-postgres
    volumes:
      - openfga_postgres:/var/lib/postgresql/data

  openfga-migrate:
    extends:
      file: ../docker-compose-base.yml
      service: openfga-migrate
    depends_on:
      openfga-postgres:
        condition: service_healthy

  openfga:
    extends:
      file: ../docker-compose-base.yml
      service: openfga
    depends_on:
      openfga-migrate:
        condition: service_completed_successfully
    command: run

  kratos-postgres:
    extends:
      file: ../docker-compose-base.yml
      service: kratos-postgres
    volumes:
      - kratos_postgres:/var/lib/postgresql/data

  kratos-migrate:
    extends:
      file: ../docker-compose-base.yml
      service: kratos-migrate
    depends_on:
      kratos-postgres:
        condition: service_healthy

  kratos:
    extends:
      file: ../docker-compose-base.yml
      service: kratos
    depends_on:
      kratos-migrate:
        condition: service_completed_successfully

  kratos-selfservice-ui-node:
    extends:
      file: ../docker-compose-base.yml
      service: kratos-selfservice-ui-node

  mailslurper:
    extends:
      file: ../docker-compose-base.yml
      service: mailslurper

  # Optional services for monitoring
  collector:
    extends:
      file: ../docker-compose-base.yml
      service: collector
    depends_on:
      - zipkin

  zipkin:
    extends:
      file: ../docker-compose-base.yml
      service: zipkin

  prometheus:
    extends:
      file: ../docker-compose-base.yml
      service: prometheus
