name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: 'ci-${{ github.event.pull_request.number || github.run_id }}'
  cancel-in-progress: true

permissions:
  actions: read
  contents: read

jobs:
  main:
    env:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - run: npm ci
      - run: npx nx report --verbose

      - name: Test OpenFGA Model
        run: |
          docker pull openfga/cli
          docker run -t openfga/cli model test --tests store.fga.yml

      - uses: nrwl/nx-set-shas@v4
      - run: npx nx affected -t lint test typecheck build
